### PR TITLE
Bug/43 cast json value to double

### LINKED ISSUE #43: settingsFile.getValue(): cannot cast returned value as double
**Pre-condition:**
1. Add new double value into any existing _object_ in `settings.json` (e.g. `"logger": { "coefficient": 0.2 }`)
2. Add getter into the configuration interface for the _object_ in `aquality.selenium.core.configurations` (e.g. ILoggerConfiguration)
3. Implement new getter in configuration class for the _object_ in `aquality.selenium.core.configurations` (e.g. `LoggerConfiguration`)

**Steps to reproduce:**
1. Open configuration class for _object_ (e.g. `LoggerConfiguration`)
2. Add new _private final double_ field (e.g `private final double coefficient;`)
3. Add this field into the class constructor casting it to `double` (e.g. `this.coefficient= (double)
                settingsFile.getValue("/logger/coefficient"`);
4. Rebuild project

**Result:**
`Error injecting constructor, java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Double`

**Expected Result:**
The value is cast to `java.lang.Double` ;

**Note:**
* Current workaround: `this.coefficient = Double.parseDouble(
                settingsFile.getValue("/swipe/horizontalSwipeBottomPointXCoefficient").toString());`
* Original discussion can be found [here](https://github.com/aquality-automation/aquality-appium-mobile-java/pull/13#discussion_r404409946).

### PR DESCRIPTION
**Pull request by knysh**
### PR Details

- cast json value to double

- rename ElementActionRetrier to ActionRetrier

##### Related Issue Link: 
closes #43 

##### Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: src/main/java/aquality/selenium/core/utilities/IActionRetrier.java [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+     * Retries the function when the handled exception {@link #getHandledExceptions()} occurs.
+     * @param function Function to be applied.
+     * @param <T> Return type of function.
+     * @return Result of the function.
+     */
+    <T> T doWithRetry(Supplier<T> function);
+
+    /**
+     * Exceptions to be ignored during action retrying.
+     * @return By the default implementation, {@link StaleElementReferenceException} and {@link InvalidElementStateException} are handled.
```
Comment (mialeska) [inline src/main/java/aquality/selenium/core/utilities/IActionRetrier.java:31]: on no, these exceptions should be in IElementActionsRetrier

File: src/main/java/aquality/selenium/core/utilities/IElementActionRetrier.java [hunk 2]
```diff
@@ -1,36 +1,8 @@
...
-    <T> T doWithRetry(Supplier<T> function);
-
-    /**
-     * Exceptions to be ignored during action retrying.
-     * @return By the default implementation, {@link StaleElementReferenceException} and {@link InvalidElementStateException} are handled.
-     */
-    default List<Class<? extends Exception>> getHandledExceptions() {
-        return Arrays.asList(StaleElementReferenceException.class, InvalidElementStateException.class);
-    }
+@Deprecated
```
Comment (mialeska) [inline src/main/java/aquality/selenium/core/utilities/IElementActionRetrier.java:6]: I believe we should not deprecate it but leave it with getHandledExceptions() and use it at Element implementation

File: src/main/java/aquality/selenium/core/elements/Element.java [hunk 3]
```diff
@@ -36,7 +36,7 @@ protected Element(final By loc, final String name, final ElementState state) {
 
     protected abstract IElementCacheConfiguration getElementCacheConfiguration();
 
-    protected abstract IElementActionRetrier getElementActionRetrier();
+    protected abstract IActionRetrier getActionRetrier();
```
Comment (mialeska) [inline src/main/java/aquality/selenium/core/elements/Element.java:39]: I believe this should remain as IElementActionRetrier

File: src/main/java/aquality/selenium/core/utilities/ElementActionRetrier.java [hunk 4]
```diff
@@ -3,52 +3,25 @@
...
-import java.util.Optional;
 import java.util.function.Supplier;
 
-public class ElementActionRetrier implements IElementActionRetrier {
-
-    private IRetryConfiguration retryConfiguration;
+/**
+ * It was renamed to ActionRetrier.
+ */
+public class ElementActionRetrier extends ActionRetrier implements IElementActionRetrier {
```
Comment (pavelanihimovsky) [inline src/main/java/aquality/selenium/core/utilities/ElementActionRetrier.java:11]: What is the difference between ElementActionRetrier and ActionRetrier?

File: src/main/java/aquality/selenium/core/utilities/IElementActionRetrier.java [hunk 5]
```diff
@@ -4,13 +4,15 @@
 import org.openqa.selenium.StaleElementReferenceException;
 
 import java.util.Arrays;
+import java.util.Collection;
 import java.util.List;
 import java.util.function.Supplier;
 
 /**
- * Retries an action or function when {@link #getHandledExceptions()} occurs.
+ * It was renamed to IActionRetrier.
```
Comment (pavelanihimovsky) [inline src/main/java/aquality/selenium/core/utilities/IElementActionRetrier.java:12]: Why do we need this comment?

File: src/main/java/aquality/selenium/core/utilities/IUtilitiesModule.java [hunk 6]
```diff
@@ -5,6 +5,13 @@
  */
 public interface IUtilitiesModule {
 
+    /**
+     * @return implementation of {@link IActionRetrier}.
+     */
+    default Class<? extends IActionRetrier> getActionRetrierImplementation() {
```
Comment (pavelanihimovsky) [inline src/main/java/aquality/selenium/core/utilities/IUtilitiesModule.java:11]: Maybe remove suffix `Implementation`?

File: src/main/java/aquality/selenium/core/utilities/ElementActionRetrier.java (hunk 4 above)
Comment (knysh) [reply src/main/java/aquality/selenium/core/utilities/ElementActionRetrier.java:8]: ElementActionRetrier handle only 2 exceptions by default (StaleElementReferenceException.class, InvalidElementStateException.class). 

ActionRetrier should handle different exceptions, depends on parameter.

File: src/main/java/aquality/selenium/core/utilities/IElementActionRetrier.java (hunk 5 above)
Comment (knysh) [reply src/main/java/aquality/selenium/core/utilities/IElementActionRetrier.java]: I didn't finish of fixes for the moment. Already fixed.

File: src/main/java/aquality/selenium/core/utilities/IUtilitiesModule.java (hunk 6 above)
Comment (knysh) [reply src/main/java/aquality/selenium/core/utilities/IUtilitiesModule.java:11]: We discussed this naming locally when implement Modules and decided to use this form, because ActionRetrier but its implementation

File: src/main/java/aquality/selenium/core/utilities/IActionRetrier.java (hunk 1 above)
Comment (knysh) [reply src/main/java/aquality/selenium/core/utilities/IActionRetrier.java]: updated

File: src/main/java/aquality/selenium/core/utilities/IElementActionRetrier.java (hunk 2 above)
Comment (knysh) [reply src/main/java/aquality/selenium/core/utilities/IElementActionRetrier.java]: updated

File: src/main/java/aquality/selenium/core/elements/Element.java (hunk 3 above)
Comment (knysh) [reply src/main/java/aquality/selenium/core/elements/Element.java]: updated

File: pom.xml [hunk 7]
```diff
@@ -5,7 +5,7 @@
     <modelVersion>4.0.0</modelVersion>
     <groupId>com.github.aquality-automation</groupId>
     <artifactId>aquality-selenium-core</artifactId>
-    <version>0.0.3</version>
+    <version>0.1.0</version>
```
Comment (pavelanihimovsky) [inline pom.xml:8]: I beleive it is time to release major version 1.0.0

File: src/main/java/aquality/selenium/core/utilities/ElementActionRetrier.java [hunk 8]
```diff
@@ -3,52 +3,22 @@
...
-                    retryAttemptsLeft--;
-                } else {
-                    throw exception;
-                }
-            }
-        }
-        return result.orElse(null);
-    }
-
-    protected boolean isExceptionHandled(Exception exception) {
```
Comment (mialeska) [inline src/main/java/aquality/selenium/core/utilities/ElementActionRetrier.java:51]: I believe this isExceptionHandled method was very handy, are you sure that we should remove it?
e.g. I have exception and want to decide handle it or not basing on exception message (like in aquality.appium.mobile for dotnet)
So - can we leave this functionality in ActionRetrier class?

File: pom.xml (hunk 7 above)
Comment (knysh) [reply pom.xml]: I don't mind

File: src/main/java/aquality/selenium/core/utilities/ElementActionRetrier.java (hunk 8 above)
Comment (knysh) [reply src/main/java/aquality/selenium/core/utilities/ElementActionRetrier.java:51]: Could you please check a fix
